name: coffee_app_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  community_material_icon: ^5.9.55
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
